name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to EC2 and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu  
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/.ssh/aiecolink-backend
            git pull origin main
            chmod +x ~/.ssh/deploy.sh
            ./deploy.sh
          command_timeout: 30m
